"""
example_summarize_titanic_data
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum

import subprocess

@aql.dataframe(task_id="aggregate_python")
def aggregate_python_func():
    bashCommand = "lscpu"
    process = subprocess.Popen(bashCommand.split(), stdout=subprocess.PIPE)
    output, error = process.communicate()

default_args={
    "owner": "sina mori,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule=None,
    start_date=pendulum.from_format("2023-11-13", "YYYY-MM-DD"),
    catchup=False,
    owner_links={
        "sina mori": "mailto:sinamori83@gmail.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/clowpmknz01qp01lmycjlo4qp/cloud-ide/clowprtio00o701mfs5estgfb/clowpru5101qs01lmr4pedhkm",
    },
)
def example_summarize_titanic_data():
    aggregate_python = aggregate_python_func()

dag_obj = example_summarize_titanic_data()
